version: "3.8"

services:
  config-server:
    image: billing-microservices/config-server
    ports:
      - "8070:8070"

  eureka-server:
    image: billing-microservices/eureka-server
    ports:
      - "8060:8060"
    depends_on:
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        max_replicas_per_node: 1
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8070

  vehicle-service:
    image: billing-microservices/vehicle-service
    ports:
      - "8090:8090"
    depends_on:
      - config-server
      - eureka-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        max_replicas_per_node: 1
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8070
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8060/eureka/

  passage-service:
    image: billing-microservices/passage-service
    ports:
      - "8091:8091"
    depends_on:
      - config-server
      - eureka-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        max_replicas_per_node: 1
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8070
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8060/eureka/


