version: "3.8"

services:
  config-server:
    image: billing-microservices/config-server
    ports:
      - "8070:8070"
  vehicle-service:
    image: billing-microservices/vehicle-service
    ports:
      - "8090:8090"
    depends_on:
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
      replicas: 1
      placement:
        max_replicas_per_node: 1
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8070


