version: "3.8"

services:
  grafana:
    image: grafana/grafana:latest
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_USER=admin
      - GF_SECURITY_ADMIN_PASSWORD=password
    depends_on:
      - prometheus

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml

  zipkin:
    image: openzipkin/zipkin
    mem_reservation: 700m
    ports:
      - "9411:9411"

  config-server:
    image: billing-microservices/config-server
    ports:
      - "8070:8070"
    depends_on:
      - zipkin
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  eureka-server:
    image: billing-microservices/eureka-server
    ports:
      - "8060:8060"
    depends_on:
      - config-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        max_replicas_per_node: 1
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8070
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  vehicle-service:
    image: billing-microservices/vehicle-service
    ports:
      - "8090:8090"
    depends_on:
      - config-server
      - eureka-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        max_replicas_per_node: 1
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8070
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8060/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  passage-service:
    image: billing-microservices/passage-service
    ports:
      - "8091:8091"
    depends_on:
      - config-server
      - eureka-server
    deploy:
      restart_policy:
        condition: on-failure
        delay: 30s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        max_replicas_per_node: 1
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8070
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8060/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

  gateway-server:
    image: billing-microservices/gateway-server
    ports:
      - "8080:8080"
    depends_on:
      - config-server
      - eureka-server
      - passage-service
      - vehicle-service
    deploy:
      restart_policy:
        condition: on-failure
        delay: 15s
        max_attempts: 3
        window: 120s
      replicas: 1
      placement:
        max_replicas_per_node: 1
    environment:
      SPRING_PROFILES_ACTIVE: default
      SPRING_CONFIG_IMPORT: configserver:http://config-server:8070
      EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server:8060/eureka/
      SPRING_ZIPKIN_BASEURL: http://zipkin:9411/

