global:
  scrape_interval: 5s
  evaluation_interval: 5s
scrape_configs:
  - job_name: 'vehicle-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['vehicle-service:8090']
  - job_name: 'passage-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'passage-service:8091' ]