apiVersion: v1
kind: ConfigMap
metadata:
  name: billing-microservices-configmap
data:
  SPRING_ZIPKIN_BASEURL: http://zipkin-service:9411/
  SPRING_PROFILES_ACTIVE: default
  SPRING_CONFIG_IMPORT: configserver:http://config-server-service:8070/
  EUREKA_CLIENT_SERVICEURL_DEFAULTZONE: http://eureka-server-service:8060/eureka/