apiVersion: apps/v1
kind: Deployment
metadata:
  name: passage-service-deployment
  labels:
    app: passage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: passage-service
  template:
    metadata:
      labels:
        app: passage-service
    spec:
      containers:
        - name: passage-service
          image: 505666/passage-service:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8091
          env:
            - name: SPRING_ZIPKIN_BASEURL
              valueFrom:
                configMapKeyRef:
                  name: billing-microservices-configmap
                  key: SPRING_ZIPKIN_BASEURL
            - name: SPRING_PROFILES_ACTIVE
              valueFrom:
                configMapKeyRef:
                  name: billing-microservices-configmap
                  key: SPRING_PROFILES_ACTIVE
            - name: SPRING_CONFIG_IMPORT
              valueFrom:
                configMapKeyRef:
                  name: billing-microservices-configmap
                  key: SPRING_CONFIG_IMPORT
            - name: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
              valueFrom:
                configMapKeyRef:
                  name: billing-microservices-configmap
                  key: EUREKA_CLIENT_SERVICEURL_DEFAULTZONE
---
apiVersion: v1
kind: Service
metadata:
  name: passage-service-service
spec:
  selector:
    app: passage-service
  ports:
    - name: http
      port: 8091
      targetPort: 8091
  type: LoadBalancer