spring:
  application:
    name: passage-service
  config:
    import: optional:configserver:http://localhost:8070
  cloud:
    config:
      name: passage-service
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411/
server:
  port: 8091
  shutdown: graceful
management:
  info.env.enabled: true
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    shutdown:
      enabled: true
eureka:
  instance:
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8060/eureka

info:
  app:
    name: Passage Microservice
    description: Billing Passage Application
    version: 1.0.0
