spring:
  application:
    name: config-server
  profiles:
    active: git
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Spot1ight/spring-cloud-properties
          clone-on-start: true
          default-label: master
#        native:
#          search-locations: classpath:/config
  sleuth:
    sampler:
      probability: 1
  zipkin:
    base-url: http://localhost:9411/
    sender:
      type: rabbit
    rabbitmq:
      queue: zipkin
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

server:
  port: 8070
encrypt:
  key: billing
#vehicle.shared: This property is shared accross all client applications